const ALLOWED_SCOPES = [
  'build',
  'ci',
  'diagnostics',
  'docs',
  'domain',
  'harness',
  'install',
  'lifecycle',
  'lyrics',
  'mpris',
  'prefs',
  'privacy',
  'product',
  'release',
  'runtime',
  'settings',
  'shell',
  'test',
];

module.exports = {
  extends: ['@commitlint/config-conventional'],
  ignores: [(message) => message.startsWith('Merge ') || message.startsWith('Revert ')],
  rules: {
    'body-max-line-length': [0],
    'footer-max-line-length': [0],
    'header-max-length': [2, 'always', 100],
    'scope-enum': [2, 'always', ALLOWED_SCOPES],
    'scope-empty': [2, 'never'],
    'subject-case': [0],
    'type-enum': [
      2,
      'always',
      [
        'build',
        'chore',
        'ci',
        'docs',
        'feat',
        'fix',
        'perf',
        'refactor',
        'revert',
        'style',
        'test',
      ],
    ],
  },
};
